FROM node:18-alpine

WORKDIR /var/www/project/

COPY ./frontend/package.json /var/www/project/

RUN npm install

COPY ./frontend/ /var/www/project/

RUN npm run format

EXPOSE 5173

CMD ["npm", "run", "dev"]