version: '3'
services:
  app-backend:
    container_name: app-curotec-techchallenge-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile-backend
    restart: on-failure:10
    volumes:
      - ./backend:/var/www
    ports:
      - 8181:8181
    depends_on:
      db:
        condition: service_healthy
      dependency-manager:
        condition: service_completed_successfully
    networks:
      - app-curotec-techchallenge-network

  dependency-manager:
    container_name: app-curotec-techchallenge-dependency-manager-backend
    build:
      context: .
      dockerfile: ./backend/DockerFile-backend-dependency-manager
    command: composer install
    volumes:
      - ./backend:/var/www

  app-frontend:
    container_name: app-curotec-techchallenge-challenge-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile-frontend
    volumes:
      - ./frontend:/var/www/project
      - /var/www/project/node_modules
    ports:
      - 5173:5173
    networks:
      - app-curotec-techchallenge-network
  
  db:
    container_name: db-curotec-techchallenge
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: techchallenge
      MYSQL_DATABASE: curotecChallenge
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-curotec-techchallenge-network

networks:
  app-curotec-techchallenge-network:
    driver: bridge